server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://%s:3306/%s?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root2018
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.sheepxi.pojo.dto
  mapper-locations: classpath:mapper/*.xml

